# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ release, dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Install dependencies
        run: npm ci
        
      - name: Check out secret
        uses: actions/checkout@master
        with:
          repository: teambebop6/anktours-secret
          token: '${{ secrets.ANKTOURS_SECRET_TOKEN }}'
          
      - name: Install Gulp globally
        run: npm install --global gulp-cli
      - run: gulp build-all      
      - run: npm run upload
        env:
          TOKEN: '${{ secrets.ANKTOURS_SECRET_TOKEN }}'
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
      - run: npm run clean-up-releases
        env:
          TOKEN: '${{ secrets.ANKTOURS_SECRET_TOKEN }}'
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
